import { Download, CheckCircle, Eye } from "lucide-react";
import Btn from "../components/ui/Btn";

export default function TokenConfirmationPage({ navigate, moduleContent, booking }) {
    const orgName = moduleContent?.orgName || "City General Hospital";
    const counterLabel = moduleContent?.counterLabel || "Counter";

    // Falls back to sensible defaults only if this page was reached without
    // an actual booking (e.g. a direct URL visit / page refresh) — normal
    // flow always has real data here.
    const b = booking || {
        department: moduleContent?.primaryDept || "General OPD",
        slot: "10:00 AM – 11:00 AM (3 slots)",
        tokenNumber: "A-042",
        peopleAhead: 8,
        estWaitMin: 24,
        counterNum: 3,
        date: new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }),
    };

    const priorityLabel = { normal: "Normal", senior: "Senior Citizen", emergency: "Emergency" }[b.priority] || "Normal";

    const details = [
        { label: "Department", value: b.department },
        ...(b.service ? [{ label: "Service", value: b.service }] : []),
        { label: `${counterLabel} Number`, value: `${counterLabel} ${b.counterNum}` },
        { label: "Queue Position", value: `#${b.peopleAhead + 1} in queue` },
        { label: "Estimated Wait", value: `~${b.estWaitMin} minutes` },
        { label: "Priority", value: priorityLabel },
        { label: "Date", value: b.date },
        { label: "Time Slot", value: b.slot },
    ];

    const handleDownload = () => {
        const lines = [
            `${orgName} — Queue Token Receipt`,
            "=".repeat(40),
            `Token Number: ${b.tokenNumber}`,
            ...details.map((d) => `${d.label}: ${d.value}`),
            "=".repeat(40),
            "Generated by Quelorax — Smart Queue & Crowd Management System",
        ];
        const blob = new Blob([lines.join("\n")], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `quelorax-token-${b.tokenNumber}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (<div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-900" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
          Token Confirmed!
        </h1>
        <p className="text-slate-500 text-sm mt-1">Your queue token has been generated successfully</p>
      </div>

      <div className="max-w-md">
        <div className="bg-white rounded-3xl shadow-lg border border-slate-100 overflow-hidden">
          <div className="bg-gradient-to-r from-blue-700 to-cyan-600 p-6 text-white text-center">
            <div className="w-14 h-14 rounded-2xl bg-white/20 flex items-center justify-center mx-auto mb-3">
              <CheckCircle size={26} className="text-white"/>
            </div>
            <p className="text-lg font-bold">Token Generated Successfully</p>
            <p className="text-blue-100 text-sm mt-1">{orgName}</p>
          </div>

          <div className="p-6">
            <div className="bg-blue-50 rounded-2xl p-5 text-center mb-6 border border-blue-100">
              <p className="text-xs text-blue-500 font-semibold mb-2 uppercase tracking-wide">Your Token Number</p>
              <p className="text-6xl font-extrabold text-blue-700 font-mono tracking-widest" style={{ fontFamily: "'DM Mono', monospace" }}>
                {b.tokenNumber}
              </p>
            </div>

            <div className="space-y-2.5 mb-6">
              {details.map((d) => (<div key={d.label} className="flex items-center justify-between py-2 border-b border-slate-50">
                  <span className="text-sm text-slate-500">{d.label}</span>
                  <span className="text-sm font-semibold text-slate-900 text-right">{d.value}</span>
                </div>))}
            </div>

            {/* QR Code */}
            <div className="flex items-center justify-center mb-6">
              <div className="bg-slate-50 rounded-2xl p-4 border border-slate-200">
                <svg width="96" height="96" viewBox="0 0 100 100">
                  {Array.from({ length: 10 }, (_, i) => Array.from({ length: 10 }, (_, j) => {
            const fill = (i + j) % 3 === 0 || (i * j) % 5 === 0
                ? "#1D4ED8"
                : (i * j) % 4 === 0
                    ? "#06B6D4"
                    : "#F1F5F9";
            return (<rect key={`${i}-${j}`} x={i * 10} y={j * 10} width={9} height={9} rx={1} fill={fill}/>);
        }))}
                </svg>
                <p className="text-xs text-slate-500 text-center mt-2">Scan to verify</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Btn variant="outline" icon={Download} className="flex-1" onClick={handleDownload}>
                Download
              </Btn>
              <Btn variant="primary" icon={Eye} className="flex-1" onClick={() => navigate("queue-tracking")}>
                Track Queue
              </Btn>
            </div>
          </div>
        </div>
      </div>
    </div>);
}
